text = {
    "welcome": "Welcome to my Geometry Tutorial.\nMy name is Ratman and we will learn geometry together",
    "next": "Please press 'space' to continue",
    "end": "The end.Please press 'space' to exit",
    "chapter1": [
        " Chapter 1",
        "Fundamental objects in geometry: Plane, Points, Lines, Rays, Line Segments",
        "In this chapter we will define the most basic concepts in geometry",
        "Here is a quick preview:",
        " - The first thing we will talk about is the Plane",
        " - Points are the second thing we will mention",
        " - Then we talk about Lines",
        " - Next are Rays also called Half Lines",
        " - And last we will talk about Line Segments",
        "                               The Plane",
        "All the next examples will happen inside of a plane\n     So what is a plane? A plane is a flat, two dimensional surface that extends infinitely far",
        "     A plane is represented by an XOY coordinate system. OX is the horizontal axis. OY is the vertical",
        "A point is an exact location. It has no size, only a position inside the plane",
        "We have drawn three points and marked them as A, B and C",
        "Each point has a coordinate inside the plane",
        "For example B's coordinates are: -6 on the OX and +2 on the OY",
        "That can be written B(-6,2)",
        "What are the approximate coordinates of A and C?",
        "                               Lines",
        "A line can be defined as a straight one-dimensional figure that has no thickness and extends endlessly in both directions.\nIt is often described as the shortest distance between any two points.",
        "We have drawn several lines.\nOnly one line can be drawn between two distinct points A and B!\nWe can write the lines as AB, CD or ED (we name two points on the line)",
        "In relation between themselves, the lines can be:",
        " - Parallel: they never meet, they are always the same distance apart\n        In our example the lines AB and CD are parallel",
        " - Intersecting: if the two lines are not parallel, it means that they intersect\n       Two distinct lines always intersect in only one point",
        " - Perpendicular: a special case where the angle between two intersecting lines is 90 degrees:\n       In our example EF is perpendicular to AB. What about CD?",
        "                               Euclid's Parallel Postulate",
        "Euclid was an ancient Greek mathematician who is considered the founder of geometry.\n     He lived in the city of Alexandria in the 3rd century BC. Where is Alexandria on the map?",
        "A postulate or an axiom is something that is considered to be true without needing a proof.\nIt is used as a starting point for further reasoning.",
        "Euclid's postulate is considered the starting point of geometry. That is why geometry is also called: Euclidean Geometry",
        "The postulate states:",
        "In a plane, given a line and a point not on it,",
        "there is one, and only one, line parallel to the given line that can be drawn through the point",
        "In our example:\n - AB was the original line\n - X was the exterior point\n - and CD is the paralel line to AB that can be drawn through X",
        "Trivia: if we negate Euclid's postulate, we get what is called Non-Euclidean geometry\nLogic: How would you negate the postulate?",
        "                               Rays and Line Segments",
        "A ray or a half-line is defined as part of a line that has a fixed starting point but no end point",
        "If we put a point on a line, that point divides the line into two rays. This is why they are also called half-lines",
        "We have drawn a line and a point A on it. So there are 2 rays starting from A.",
        "In order to name them, we need to add two more points on the line",
        "We now have the rays [AX and [AY\n - We put a parenthesis before A to signify that A is the starting point of the ray\n - We leave X and Y open to signify that the ray goes to infinity",
        "A line segment is a part of a line that is bounded by two distinct end points and contains every point on the line between its end points",
        " - Depending on how the line segment is defined, either of the two end points may or may not be part of the line segment",
        "We have drawn several line segments:",
        " - [AB] is a segment with A and B points included or closed line segment",
        " - (CD) is called an open line segment because C and D are not included",
        "The relationships between lines transfer to line segments, plus some additional ones:",
        " - [AB] and [CD] are parallel line segments",
        " - [AB] and [EF] are perpendicular line segments. Why?",
        " - [AB] and [GH] are called collinear because they are part of the same line",
        " - [AB] and [IJ] are just coplanar, meaning they are in the same plane",
        " - When it comes to size, [AB] is congruent to [IJ] because they have the same length"

    ],
    "chapter2": [
        "   Welcome to the Second Chapter\n\n\nHere we will talk about angles",
    ]

}