text = {
    "welcome": "                Hola bienvenido a mi tutorial de geometria\n\n      Mi nombre es Bogdan y vamos a aprender geometria",
    "next": "Apreta 'espacio' para continuar",
    "end": "Fin. Apreta 'espacio' para salir",
    "chapter1": [
        "Capitulo 1",
        "Objetos fundamentales en geometria: Plano, Puntos, Rectas, Semirrectas, Segmentos",
        "En este capitulo vamos a ver los objetos mas basicos de geometria",
        "Aqui es un anticipe:",
        " - La primera cosa va a ser el Plano",
        " - Los Puntos son la segunda cosa que vamos a ver",
        " - Mas tarde Rectas",
        " - Despues Semirrectas",
        " - Y lo ultimo: Segmentos",
        "                               El Plano",
        "Los siguentes ejemplos seran en un plano\n     Que es un plano? Un plano es una superficie bidimensional que se extiende infinitamente lejos",
        "     Un plano esta representado de un sistema de curdenadas XOY. OX es el axis horizontal. OY es el vertical",
        "Un punto es una locacion exacta. No tiene tamaño, solo una pocision dentro del plano",
        "Hemos dibujado tres puntos y los hemos marcado como 'A' 'B' y 'C'",
        "Cada punto tiene una cordenada dentro del plano",
        "Por ejemplo las cordenadas de 'B' son: -6 en OX y +2 en OY",
        "Se escribe asi B(-6,2)",
        "Cuales son las cordenadas de A y C?",
        "                               Las Rectas",
        "Una recta o una linea recta se puede describir a sucesión continua de puntos extendidos en una sola dirección.\nA menudo se describe como la distancia más corta entre dos puntos.",
        "Hemos dibujado varias líneas.\n¡Solo se puede dibujar una línea entre dos puntos distintos A y B!\nPodemos escribir las líneas como AB, CD o ED (nombramos dos puntos en la línea)",
        "En relación entre ellos, las líneas pueden ser:",
        " - Paralelo: nunca se encuentran, siempre están a la misma distancia\n         En nuestro ejemplo, las líneas AB y CD son paralelas",
        " - Intersectado: si las dos rectas no son paralelas, significa que se cruzan\n         Dos líneas distintas siempre se cruzan en un solo punto",
        " - Perpendicular: un caso especial donde el ángulo de intersección entre dos rectas es de 90 grados:\n     En nuestro ejemplo, EF es perpendicular a AB. ¿Qué pasa con CD?",
        "                   El postulado de las paralelas o quinto postulado de Euclides",
        "Euclides fue un antiguo matemático griego considerado el fundador de la geometría.\n   Vivió en la ciudad de Alejandría en el siglo III a.C. ¿Dónde está Alexandria en el mapa?",
        "Un postulado o un axioma es algo que se considera verdadero sin necesidad de una prueba.\nSe utiliza como punto de partida para un mayor razonamiento.",
        "El postulado de Euclides se considera el punto de partida de la geometría. Por eso también se llama Geometría Euclidiana",
        "El postulado declara:",
        "En un plano, dada una línea y un punto que no está en ella,",
        "hay una, y solo una, recta paralela a la recta dada que se puede dibujar a través del punto",
        "En nuestro ejemplo:\n - AB era la línea original\n - X era el punto exterior\n - y CD es la recta paralela a AB que se puede dibujar a través de X",
        "Trivia: si negamos el postulado de Euclides, obtenemos lo que se llama geometría no euclidiana\nLógica: ¿Cómo negarías el postulado?",
        "                               Semirrectas y Segmentos",
        "Una semirrecta se define como parte de una línea que tiene un punto de inicio fijo pero no tiene un punto final",
        "Si ponemos un punto en una recta, ese punto divide la recta en dos semirrectas.",
        "Hemos dibujado una recta y un punto A en ella. Entonces hay 2 semirrectas a partir de A.",
        "Para nombrarlos, necesitamos agregar dos puntos más en la línea",
        "Ahora tenemos los semirrectas [AX y [AY\n - Ponemos un paréntesis antes de A para indicar que A es el punto de partida de la semirrecta\n - Dejamos X e Y abiertos para indicar que la semirrecta va al infinito",
        "Un segmento es una parte de una recta que está limitada por dos puntos finales distintos y contiene todos los puntos de la recta entre sus puntos finales.",
        " - Dependiendo de cómo se define el segmento, cualquiera de los dos puntos finales puede o no ser parte del segmento",
        "Hemos dibujado varios segmentos de línea:",
        " - [AB] es un segmento con puntos A y B incluidos o segmento cerrado",
        " - (CD) se llama segmento abierto porque C y D no están incluidos",
        "Las relaciones entre líneas se transfieren a segmentos, más algunos adicionales:",
        " - [AB] y [CD] son segmentos paralelos",
        " - [AB] y [EF] son segmentos perpendiculares. ¿Por qué?",
        " - [AB] y [GH] se llaman colineales porque son parte de la misma línea",
        " - [AB] y [IJ] son simplemente coplanares, lo que significa que están en el mismo plano",
        " - Cuando se trata de tamaño, [AB] es congruente con [IJ] porque tienen la misma longitud"

    ],
    "chapter2": [
        "   Welcome to the Second Chapter\n\n\nHere we will talk about angles",
    ]

}